name: Build

on:
  push:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller --onefile --windowed main.py
      - uses: actions/upload-artifact@v4
        with:
          name: app-linux
          path: dist/main

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller --onefile --windowed main.py
      - uses: actions/upload-artifact@v4
        with:
          name: app-windows
          path: dist/main.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller --onefile --windowed main.py
      - uses: actions/upload-artifact@v4
        with:
          name: app-macos
          path: dist/main
